<<<<<<< HEAD
trigger:
  branches:
    include:
      - main
      - develop
      - 'feature/*'
      - 'release/*'

resources:
  repositories:
  - repository: templates
    type: github
    name: Royce21/ado-pipeline-templates
    ref: refs/heads/main          # later switch to refs/tags/v1.x.x
    endpoint: github-templates-conn

extends:
  template: pipelines/multi-stage.yml@templates
  parameters:
    app_type: dotnet              # or: node
    env: qa                       # dev | qa | prod
    enable_deploy: true           # false => CI only
    vmImage: ubuntu-latest
    artifact_name: drop
    service_connection: my-qa-sp-connection
    path_filter:
      include:
        - 'src/service-a/*'
      exclude:
        - 'docs/*'
=======
﻿trigger: none
pr: none
schedules: []
pool: { vmImage: ubuntu-latest }
steps:
- script: echo "Templates repo has no CI; triggers disabled."
  displayName: No-op
>>>>>>> cf3ccb4 (chore: no-op pipeline; update templates)
