# ado-pipeline-templates/pipelines/multi-stage.yml
# Entry point templates consumers will extend
parameters:
- name: app_type
  type: string
  values: [dotnet, node]
- name: env
  type: string
  values: [dev, qa, prod]
- name: enable_deploy
  type: boolean
  default: false
- name: vmImage
  type: string
  default: 'ubuntu-latest'
- name: artifact_name
  type: string
  default: 'drop'
- name: service_connection
  type: string
  default: ''
- name: path_filter
  type: object
  default:
    include: []
    exclude: []

stages:
- template: ../stages/ci.yml
  parameters:
    app_type:       ${{ parameters.app_type }}
    vmImage:        ${{ parameters.vmImage }}
    artifact_name:  ${{ parameters.artifact_name }}
    path_filter:    ${{ parameters.path_filter }}

- ${{ if eq(parameters.enable_deploy, true) }}:
  - template: ../stages/cd.yml
    parameters:
      env:                ${{ parameters.env }}
      vmImage:            ${{ parameters.vmImage }}
      artifact_name:      ${{ parameters.artifact_name }}
      service_connection: ${{ parameters.service_connection }}
