# ado-pipeline-templates/pipelines/multi-stage.yml
parameters:
- name: app_type
  type: string
  default: dotnet
  values: [dotnet, node]

- name: env
  type: string
  default: dev
  values: [dev, qa, prod]

- name: enable_deploy
  type: boolean
  default: false

- name: vmImage
  type: string
  default: ubuntu-latest

- name: artifact_name
  type: string
  default: drop

- name: service_connection
  type: string
  default: ""

- name: path_filter
  type: object
  default:
    include: []
    exclude: []

- name: var_groups
  type: object
  default: []

stages:
# -------- CI --------
- template: ../stages/ci.yml
  parameters:
    app_type:      ${{ parameters.app_type }}
    vmImage:       ${{ parameters.vmImage }}
    artifact_name: ${{ parameters.artifact_name }}
    path_filter:   ${{ parameters.path_filter }}

# -------- CD --------
# Always include the CD template and do gating INSIDE cd.yml via a stage condition.
- template: ../stages/cd.yml
  parameters:
    enable_deploy:      ${{ parameters.enable_deploy }}
    env:                ${{ parameters.env }}
    vmImage:            ${{ parameters.vmImage }}
    artifact_name:      ${{ parameters.artifact_name }}
    service_connection: ${{ parameters.service_connection }}
    var_groups:         ${{ parameters.var_groups }}
