# ado-pipeline-templates/stages/ci.yml
parameters:
- name: app_type
  type: string
  # you can constrain if you want:
  # values: [dotnet, node]
- name: vmImage
  type: string
  default: 'ubuntu-latest'
- name: artifact_name
  type: string
- name: path_filter
  type: object
  default:
    include: []
    exclude: []

stages:
- stage: CI
  displayName: "Build & Test"
  variables:
    vmImageName: ${{ parameters.vmImage }}
  jobs:
  # .NET CI job (included only if app_type == 'dotnet')
  - ${{ if eq(parameters.app_type, 'dotnet') }}:
    - job: dotnet_ci
      displayName: "Build & Test (.NET)"
      pool:
        vmImage: $(vmImageName)
      steps:
      - checkout: self
        fetchDepth: 0
      - template: ../jobs/dotnet-build-test.yml
        parameters:
          artifact_name: ${{ parameters.artifact_name }}

  # Node CI job (included only if app_type == 'node')
 - ${{ if eq(parameters.app_type, 'dotnet') }}:
  - job: dotnet_ci
    displayName: "Build & Test (.NET)"
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      fetchDepth: 0
    - template: ../jobs/dotnet-build-test.yml
      parameters:
        artifact_name: ${{ parameters.artifact_name }}
