# ado-pipeline-templates/stages/ci.yml
parameters:
- name: app_type
  type: string
- name: vmImage
  type: string
  default: 'ubuntu-latest'
- name: artifact_name
  type: string
- name: path_filter
  type: object
  default:
    include: []
    exclude: []

stages:
- stage: CI
  displayName: "Build & Test"
  variables:
    vmImageName: ${{ parameters.vmImage }}   # <-- set once here
  jobs:
  - job: build_test
    displayName: "Build and Test"
    pool:
      vmImage: $(vmImageName)                # <-- use the variable, not a template expr
    steps:
    - checkout: self
      fetchDepth: 0

    # Language-specific jobs
    - ${{ if eq(parameters.app_type, 'dotnet') }}:
       template: ../jobs/dotnet-build-test.yml
       parameters:
          artifact_name: ${{ parameters.artifact_name }}
          project_dir: $(Build.SourcesDirectory)/src/service-a     # ← adjust after you see the logged path
          projects_glob: '**/*.sln'
    - ${{ if eq(parameters.app_type, 'node') }}:
      - template: ../jobs/node-build-test.yml
        parameters:
          artifact_name: ${{ parameters.artifact_name }}
          project_dir: $(Build.SourcesDirectory)/packages/lib-xyz
