# ado-pipeline-templates/stages/ci.yml
parameters:
- name: app_type
  type: string
  default: dotnet
  values: [dotnet, node]
- name: vmImage
  type: string
  default: ubuntu-latest
- name: artifact_name
  type: string
  default: drop
- name: path_filter
  type: object
  default:
    include: []
    exclude: []

stages:
- stage: CI
  displayName: Build and Test
  variables:
    vmImageName: ${{ parameters.vmImage }}
    AppType: ${{ parameters.app_type }}

  jobs:
  - ${{ if eq(parameters.app_type, 'dotnet') }}:
    - job: dotnet_ci
      displayName: Build and Test - dotnet
      pool: { vmImage: $(vmImageName) }
      steps:
      - checkout: self
        fetchDepth: 0
      - template: ../jobs/dotnet-build-test.yml
        parameters:
          artifact_name: ${{ parameters.artifact_name }}

  - ${{ if eq(parameters.app_type, 'node') }}:
    - job: node_ci
      displayName: Build and Test - node
      pool: { vmImage: $(vmImageName) }
      steps:
      - checkout: self
        fetchDepth: 0
      - template: ../jobs/node-build-test.yml
        parameters:
          artifact_name: ${{ parameters.artifact_name }}
