# ado-pipeline-templates/stages/ci.yml
parameters:
- name: app_type
  type: string
  # values: [dotnet, node]   # optional
- name: vmImage
  type: string
  default: 'ubuntu-latest'
- name: artifact_name
  type: string
- name: path_filter
  type: object
  default:
    include: []
    exclude: []

stages:
- stage: CI
  displayName: "Build & Test"
  variables:
    vmImageName: ${{ parameters.vmImage }}
    AppType:     ${{ parameters.app_type }}

  jobs:
  # .NET job (runs only if app_type == dotnet)
  - job: dotnet_ci
    displayName: "Build & Test (.NET)"
    condition: and(succeeded(), eq(variables['AppType'], 'dotnet'))
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      fetchDepth: 0
    - template: ../jobs/dotnet-build-test.yml
      parameters:
        artifact_name: ${{ parameters.artifact_name }}

  # Node job (runs only if app_type == node)
  - job: node_ci
    displayName: "Build & Test (Node)"
    condition: and(succeeded(), eq(variables['AppType'], 'node'))
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      fetchDepth: 0
    - template: ../jobs/node-build-test.yml
      parameters:
        artifact_name: ${{ parameters.artifact_name }}
