# ado-pipeline-templates/stages/ci.yml
parameters:
- name: app_type
  type: string
- name: vmImage
  type: string
  default: ubuntu-latest
- name: artifact_name
  type: string
- name: path_filter
  type: object
  default:
    include: []
    exclude: []

stages:
- stage: CI
<<<<<<< HEAD
  displayName: Build and Test
  variables:
    vmImageName: ${{ parameters.vmImage }}
    AppType:     ${{ parameters.app_type }}

  jobs:
  - job: dotnet_ci
    displayName: Build and Test - dotnet
    condition: and(succeeded(), eq(variables['AppType'], 'dotnet'))
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      fetchDepth: 0
    - template: ../jobs/dotnet-build-test.yml
      parameters:
        artifact_name: ${{ parameters.artifact_name }}

  - job: node_ci
    displayName: Build and Test - node
    condition: and(succeeded(), eq(variables['AppType'], 'node'))
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      fetchDepth: 0
    - template: ../jobs/node-build-test.yml
      parameters:
        artifact_name: ${{ parameters.artifact_name }}
=======
  displayName: "Build & Test"
  jobs:
  - job: build_test
    displayName: "Build and Test"
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - checkout: self
      fetchDepth: 0

    - ${{ if eq(parameters.app_type, 'dotnet') }}:
      - template: ../jobs/dotnet-build-test.yml
        parameters:
          artifact_name: ${{ parameters.artifact_name }}

    - ${{ if eq(parameters.app_type, 'node') }}:
      - template: ../jobs/node-build-test.yml
        parameters:
          artifact_name: ${{ parameters.artifact_name }}
>>>>>>> cf3ccb4 (chore: no-op pipeline; update templates)
